services:
  vox-postgres:
    image: postgres:18.4
    container_name: vox-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./infrastructure/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 10

  vox-keycloak:
    image: quay.io/keycloak/keycloak:26.7.0-0
    container_name: vox-keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: vox-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root

      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

    volumes:
      - ./infrastructure/keycloak/realm:/opt/keycloak/data/import

    depends_on:
      vox-postgres:
        condition: service_healthy

volumes:
  postgres_data: